"""Stream M, step 5: the per-batch case tables, built from the STAGED exams (read-only on J:).

    python mri_04_cases.py [--dedup-only]   # M01..M08 (+ convert results when present) and the DEDUP proof set

For every exam of a batch (plan_exams.csv, disposition register), from its staged copy:
  drv_acq_datetime   exam visu_pars VisuCreationDate (the value production's MRI ingest uses,
                     paravision_metadata 'mri_acquisition_datetime'), else acqp ACQ_time. Never empty: an exam with
                     neither stops this script (the ingest would date it TODAY).
  drv_alias, drv_animal          the facility-DB lookup (subject_lookup) -> <animal>-AE-biomaGUNE-<alias>
  drv_sample, drv_session, drv_project, drv_model, drv_note, drv_dicom_origin
and the planned project-link name MRI_<sample>_<YYYYMMDD>_<exam>_<every pdata idx> (the production template).
Writes tools/configs/drive3_mri/cases_<batch>.csv, out\\cases_check.txt and out\\link_names.csv. For DEDUP it writes
cases_DEDUP.csv and out\\dedup_date_check.csv: the rule's date against the date of production's row of the same name.

An exam of class (d) must have a convert result (out\\convert_<batch>.csv, from convert_staged_exams.py in WSL):
'converted' rows are kept with drv_dicom_origin = Dicomifier; any other status removes the exam from the case table
and adds it to out\\not_registered_after_convert.csv. A (c) exam must hold DICOM in its staged copy.
"""
import collections
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mri_common as C  # noqa: E402

sys.path.insert(0, os.path.join(C.WT, "tools"))
from ingest import jcampdx  # noqa: E402

BATCHES = ["M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09"]
ORIGIN = {"c": "scanner-exported DICOM",
          "d": "DICOM regenerated by Dicomifier 2.5.3 (+ gjesus3 workarounds) from the ParaVision 2dseq before ingest"}
SERIAL = "WX22D623YP29"


def clean(v):
    if isinstance(v, list):
        v = v[0] if v else ""
    return str(v or "").strip().strip("<>").strip()


def exam_dates(ex):
    v = clean(jcampdx.parse_file(os.path.join(ex, "visu_pars")).get("VisuCreationDate"))
    if v:
        return v, "visu_pars.VisuCreationDate"
    a = clean(jcampdx.parse_file(os.path.join(ex, "acqp")).get("ACQ_time"))
    if a:
        return a, "acqp.ACQ_time"
    return "", ""


def recon_dirs(ex):
    root = os.path.join(ex, "pdata")
    if not os.path.isdir(root):
        return []
    return sorted((d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))),
                  key=lambda x: int(x) if x.isdigit() else x)


def note(p, origin):
    if p["batch"] == "M08":
        claim = ("no project and no subject id: the folder claims 0619, but animal 174 of 0619 was born on 2021-07-29 "
                 "(facility DB), two years after this scan (A1 2.6)")
        who = f"animal m{p['animal']} per the study name"
    elif p["batch"] == "M09":
        claim = ("protocol 0619 (folder claim), NO subject id: the name claims animal 145b, which the facility DB does not "
                 "hold; 145 has its own session that day (jrc210726_m145_0619), and the DB logs MRI 7T on 2021-07-26 "
                 "for 145, 146, 152 and 153 -- so probably 146, unconfirmed")
        who = "animal m145b per the study name"
    else:
        claim = f"protocol {p['protocol']} ({p['verdict']} in the facility DB)"
        who = f"animal {p['sample_id'].split('_')[0]}"
    return (f"{who}, {claim}; historical drive 3 (M. Jesus, MJesus-MFB, WD {SERIAL}): {p['drive_exam_dir']}; {origin}; "
            f"to be checked against the MRI platform's archive (BACKLOG)")


def build(batch, plan, conv, notreg_after):
    out_rows, links, problems = [], [], []
    for p in plan:
        ex = os.path.join(C.STAGE, batch, p["study"], p["exam"])
        if not os.path.isdir(ex):
            problems.append(f"{p['original_name']}: not staged")
            continue
        if p["class"] == "d":
            c = conv.get(p["original_name"])
            if c is None:
                problems.append(f"{p['original_name']}: class d with no convert result")
                continue
            if c["status"] != "converted":
                notreg_after.append({**p, "reason": f"{c['status']}: {c['reason']}"})
                continue
        dcm = glob.glob(os.path.join(ex, "pdata", "*", "dicom", "*.dcm"))
        if not dcm:
            problems.append(f"{p['original_name']}: no DICOM in the staged exam")
            continue
        dt, src = exam_dates(ex)
        if not dt:
            problems.append(f"{p['original_name']}: no VisuCreationDate and no ACQ_time")
            continue
        origin = ORIGIN[p["class"]]
        idx = recon_dirs(ex)
        link = f"MRI_{p['sample_id']}_{dt[:10].replace('-', '')}_{p['exam']}_{','.join(idx)}"
        out_rows.append({"original_name": p["original_name"], "drv_acq_datetime": dt, "drv_acq_time_source": src,
                         "drv_alias": p["alias"], "drv_animal": p["animal"], "drv_sample": p["sample_id"],
                         "drv_session": p["session_id"], "drv_project": p["project_name"], "drv_model": p["model"],
                         "drv_dicom_origin": origin, "drv_note": note(p, origin)})
        links.append({"batch": batch, "original_name": p["original_name"], "project_name": p["project_name"],
                      "link_name": link, "n_dcm": len(dcm), "acq_date": dt[:10], "acq_time_date": p["acq_time"][:10],
                      "date_source": src})
    return out_rows, links, problems


def main():
    plan = [p for p in C.rows(os.path.join(C.OUT, "plan_exams.csv")) if p["disposition"] == "register"]
    os.makedirs(C.CFG_DIR, exist_ok=True)
    L, all_links, notreg_after, all_problems = [], [], [], []
    for b in ([] if "--dedup-only" in sys.argv else BATCHES):
        bp = [p for p in plan if p["batch"] == b]
        cpath = os.path.join(C.OUT, f"convert_{b}.csv")
        conv = {r["original_name"]: r for r in C.rows(cpath)} if os.path.exists(cpath) else {}
        rows_, links, problems = build(b, bp, conv, notreg_after)
        all_problems += problems
        all_links += links
        if rows_:
            C.write_csv(os.path.join(C.CFG_DIR, f"cases_{b}.csv"), rows_)
        src = collections.Counter(r["drv_acq_time_source"] for r in rows_)
        L.append(f"{b}: planned {len(bp)}; in case table {len(rows_)}; date source {dict(src)}; problems {len(problems)}")
    # link names: unique within the stream (case-insensitive) and free in each project's raw_linked now
    seen = collections.defaultdict(list)
    for l in all_links:
        seen[(l["project_name"], l["link_name"].lower())].append(l["original_name"])
    within = {k: v for k, v in seen.items() if len(v) > 1 and k[0]}
    taken = []
    for proj in sorted({l["project_name"] for l in all_links if l["project_name"]}):
        existing = {n.lower() for n in os.listdir(os.path.join(C.NAS, "projects", proj, "raw_linked"))}
        taken += [l for l in all_links if l["project_name"] == proj and l["link_name"].lower() in existing]
    date_off = [l for l in all_links if l["acq_date"] != l["acq_time_date"]]
    C.write_csv(C.out("link_names.csv"), all_links)
    C.write_csv(C.out("not_registered_after_convert.csv"), notreg_after,
                list(plan[0].keys()) + ["reason"] if plan else None)
    L.append(f"link names: {len(all_links)}; duplicated within the stream: {len(within)}; already taken in production "
             f"now: {len(taken)} {[t['link_name'] for t in taken[:5]]}")
    L.append(f"exams whose case-table date differs from the scan date (acqp ACQ_time): {len(date_off)} "
             f"{[(d['original_name'], d['acq_date'], d['acq_time_date']) for d in date_off[:8]]}")
    L.append(f"not registered after conversion: {len(notreg_after)}")
    L.append(f"problems: {len(all_problems)} {all_problems[:10]}")

    # ---- the dedup proof set ---------------------------------------------------------------------------------
    dd = C.rows(os.path.join(C.OUT, "plan_dedup_exams.csv"))
    drows, check = [], []
    for p in dd:
        ex = os.path.join(C.STAGE, "DEDUP", p["study"], p["exam"])
        dt, src = exam_dates(ex) if os.path.isdir(ex) else ("", "")
        drows.append({"original_name": f"{p['study']}/{p['exam']}", "drv_acq_datetime": dt, "drv_acq_time_source": src})
        check.append({**p, "rule_date": dt[:10], "rule_source": src,
                      "agrees": "Y" if dt and dt[:10] in p["prod_dates"].split(";") else "N"})
    # an exam with no date anywhere (never acquired) cannot take part in a date-keyed proof: production's own rows for
    # them are undated placeholders. They are left out of the table; the proof config skips them by name, visibly.
    if dd:
        C.write_csv(os.path.join(C.CFG_DIR, "cases_DEDUP.csv"), [r for r in drows if r["drv_acq_datetime"]])
    C.write_csv(C.out("dedup_date_check.csv"), check)
    agree = collections.Counter((c["agrees"], c["rule_source"]) for c in check)
    L.append(f"DEDUP: {len(dd)} exams; the rule's date equals production's row date: {dict(agree)}; "
             f"disagreements {[(c['exam_key'], c['rule_date'], c['prod_dates'], c['prod_configs']) for c in check if c['agrees'] == 'N'][:8]}")
    open(C.out("cases_check.txt"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("\n".join(L))
    sys.exit(1 if all_problems or within or taken else 0)


if __name__ == "__main__":
    main()
