"""Stream AR, step 8: the per-batch case tables, built from the EXTRACTED (and converted) exams; and the dedup proof.

    python ar_07_cases.py [--dedup-only] [<batch> ...]     (default: every batch)

For every exam of a batch that registers (out\\plan_exams.csv: register, or convert-first with a 'converted' result in
out\\convert_<batch>.csv), from its folder extract\\<batch>\\<study>\\<exam>\\:
  drv_acq_datetime   exam visu_pars VisuCreationDate (production's rule), else acqp ACQ_time; never empty
  drv_alias, drv_animal, drv_sample, drv_sample_type, drv_session, drv_project, drv_model, drv_hhmm (the study start),
  drv_dicom_origin, drv_note
and the planned link name MRI_<sample>_<YYYYMMDD>_<HHMM>_<exam>_<every pdata idx> (the 2026-10-05 convention).
A convert-first exam whose conversion did not succeed leaves the case table (out\\not_registered_after_convert.csv).
Writes tools\\configs\\mri_archive\\cases_<batch>.csv, out\\link_names.csv, out\\cases_check.txt.

THE DEDUP PROOF (cases_DEDUP.csv): every exam of the 130 tier-C studies (stream M's, in production since 2026-10-07)
that production holds, staged as extract\\C\\<study>\\<exam> and dated by the same rule: a dry run must skip every one
as already registered and list none (stream M gate 2.3). Exams with no date anywhere are left out (and reported).
"""
import collections
import glob
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ar_common as C  # noqa: E402

sys.path.insert(0, os.path.join(C.WT, "tools"))
from ingest import jcampdx  # noqa: E402

ORIGIN = {"register": "scanner-exported DICOM",
          "convert-first": "DICOM regenerated by Dicomifier 2.5.3 (+ gjesus3 workarounds) from the ParaVision 2dseq before ingest"}


def clean(v):
    if isinstance(v, list):
        v = v[0] if v else ""
    return str(v or "").strip().strip("<>").strip()


def exam_dates(ex):
    p = os.path.join(ex, "visu_pars")
    v = clean(jcampdx.parse_file(p).get("VisuCreationDate")) if os.path.isfile(p) else ""
    if v:
        return v, "visu_pars.VisuCreationDate"
    p = os.path.join(ex, "acqp")
    a = clean(jcampdx.parse_file(p).get("ACQ_time")) if os.path.isfile(p) else ""
    return (a, "acqp.ACQ_time") if a else ("", "")


def recon_dirs(ex):
    root = os.path.join(ex, "pdata")
    if not os.path.isdir(root):
        return []
    return sorted((d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))),
                  key=lambda x: (0, int(x)) if x.isdigit() else (1, x))


def note(x, s, origin):
    who = (f"animal {x['animal_token']}" if x["kind"] == "animal" else f"{s['sample_type']} study (phantom / QC, Q2)")
    if x["project_name"] and s["db_verdict"] == "DB-RESOLVED":
        claim = (f"protocol {s['project_name'][-4:]} by the facility DB (no code in the name; one protocol holds the "
                 f"animal with MRI logged: {s['db_evidence']})")
    elif x["project_name"] and x["alias"]:
        claim = f"protocol {s['claim']} ({s['db_verdict']} in the facility DB)"
    elif x["project_name"]:
        claim = s["why"]
    else:
        claim = s["why"]
    arc = s["archive"].split("backup_7T_olddata_260824/")[-1]
    return (f"{who}; {claim}; MRI platform archive backup_7T_olddata_260824/{arc} (SHA-1 {s['archive_sha1']}); "
            f"{origin}; operator pending claim (historical MRI, STATUS 0.5 Hold)")


def build(batch, xs, studies, conv, notreg_after):
    rows, links, problems = [], [], []
    for x in xs:
        s = studies[x["study"]]
        ex = os.path.join(C.EXTRACT, batch, x["study"], x["exam"])
        if not os.path.isdir(ex):
            problems.append(f"{x['original_name']}: not in extract\\{batch}")
            continue
        if x["disposition"] == "convert-first":
            c = conv.get(x["original_name"])
            if c is None:
                problems.append(f"{x['original_name']}: convert-first with no convert result")
                continue
            if c["status"] != "converted":
                notreg_after.append({**x, "reason": f"{c['status']}: {c['reason']}"})
                continue
        dcm = glob.glob(os.path.join(ex, "pdata", "*", "dicom", "*.dcm"))
        if not dcm:
            problems.append(f"{x['original_name']}: no DICOM in the exam")
            continue
        dt, src = exam_dates(ex)
        if not dt:
            problems.append(f"{x['original_name']}: no VisuCreationDate and no ACQ_time")
            continue
        origin = ORIGIN[x["disposition"]]
        idx = recon_dirs(ex)
        link = (f"MRI_{x['sample_id']}_{dt[:10].replace('-', '')}_{x['study_hhmm']}_{x['exam']}_{','.join(idx)}"
                if x["project_name"] else "")
        x = {**x, "animal_token": s["sample_id"].split("_")[0]}
        rows.append({"original_name": x["original_name"], "drv_acq_datetime": dt, "drv_acq_time_source": src,
                     "drv_alias": x["alias"], "drv_animal": x["animal"], "drv_sample": x["sample_id"],
                     "drv_sample_type": x["sample_type"], "drv_session": x["session_id"],
                     "drv_project": x["project_name"], "drv_model": x["model"], "drv_hhmm": x["study_hhmm"],
                     "drv_dicom_origin": origin, "drv_note": note(x, s, origin)})
        links.append({"batch": batch, "original_name": x["original_name"], "project_name": x["project_name"],
                      "link_name": link, "n_dcm": len(dcm), "acq_date": dt[:10], "date_source": src})
    return rows, links, problems


def main():
    plan = C.rows(os.path.join(C.OUT, "plan_exams.csv"))
    studies = {s["study"]: s for s in C.rows(os.path.join(C.OUT, "plan_studies.csv"))}
    os.makedirs(C.CFG_DIR, exist_ok=True)
    L, all_links, notreg_after, all_problems = [], [], [], []
    batches = sorted({x["batch"] for x in plan if x["disposition"] != "not-registered"})
    only = [a for a in sys.argv[1:] if a.startswith("AR")]
    if only:
        batches = [b for b in batches if b in only]
    for b in ([] if "--dedup-only" in sys.argv else batches):
        xs = [x for x in plan if x["batch"] == b and x["disposition"] != "not-registered"]
        cpath = os.path.join(C.OUT, f"convert_{b}.csv")
        conv = {r["original_name"]: r for r in C.rows(cpath)} if os.path.exists(cpath) else {}
        rows_, links, problems = build(b, xs, studies, conv, notreg_after)
        all_problems += problems
        all_links += links
        C.write_csv(os.path.join(C.CFG_DIR, f"cases_{b}.csv"), rows_,
                    ["original_name", "drv_acq_datetime", "drv_acq_time_source", "drv_alias", "drv_animal", "drv_sample",
                     "drv_sample_type", "drv_session", "drv_project", "drv_model", "drv_hhmm", "drv_dicom_origin", "drv_note"])
        L.append(f"{b}: planned {len(xs)} ({sum(1 for x in xs if x['disposition'] == 'convert-first')} convert-first); "
                 f"in case table {len(rows_)}; date source {dict(collections.Counter(r['drv_acq_time_source'] for r in rows_))}; "
                 f"problems {len(problems)}")
    if all_links:
        seen = collections.defaultdict(list)
        for l in all_links:
            if l["link_name"]:
                seen[(l["project_name"], l["link_name"].lower())].append(l["original_name"])
        within = {k: v for k, v in seen.items() if len(v) > 1}
        taken = []
        for proj in sorted({l["project_name"] for l in all_links if l["project_name"]}):
            rl = os.path.join(C.NAS, "projects", proj, "raw_linked")
            existing = {n.lower() for n in os.listdir(rl)} if os.path.isdir(rl) else set()
            taken += [l for l in all_links if l["project_name"] == proj and l["link_name"].lower() in existing]
        C.write_csv(C.out("link_names.csv"), all_links)
        C.write_csv(C.out("not_registered_after_convert.csv"), notreg_after,
                    list(plan[0].keys()) + ["reason"] if plan else None)
        L.append(f"case rows {len(all_links)}; link names {sum(1 for l in all_links if l['link_name'])}; duplicated within "
                 f"the stream: {len(within)}; already taken in production now: {len(taken)} {[t['link_name'] for t in taken[:5]]}")
        L.append(f"not registered after conversion: {len(notreg_after)}")
        L.append(f"problems: {len(all_problems)} {all_problems[:10]}")
    else:
        within, taken = {}, []

    # ---- the dedup proof set: tier C exams that production holds (stream M's list, with an ACQ-ID) ---------------
    lst = C.rows(os.path.join(C.WT, "tasks", "drive3_mri_for_archive_check.csv"))
    held = {r["original_name"]: r for r in lst if r["acq_id"]}
    drows, nodate, absent = [], [], []
    for on, r in sorted(held.items()):
        ex = os.path.join(C.EXTRACT, "C", *on.split("/"))
        if not os.path.isdir(ex):
            absent.append(on)
            continue
        dt, src = exam_dates(ex)
        if not dt:
            nodate.append(on)
            continue
        drows.append({"original_name": on, "drv_acq_datetime": dt, "drv_acq_time_source": src,
                      "prod_acq_id": r["acq_id"], "prod_datetime": r["acq_datetime"],
                      "same_day": "Y" if dt[:10] == r["acq_datetime"][:10] else "N"})
    C.write_csv(os.path.join(C.CFG_DIR, "cases_DEDUP.csv"), drows,
                ["original_name", "drv_acq_datetime", "drv_acq_time_source"])
    C.write_csv(C.out("dedup_set.csv"), drows)
    L.append(f"DEDUP set: production holds {len(held)} of stream M's exams; in the extracted tier C {len(drows) + len(nodate)}; "
             f"with a date {len(drows)} (archive date's day == production's: {dict(collections.Counter(d['same_day'] for d in drows))}); "
             f"no date {len(nodate)}; not in the extracted archive copy {len(absent)}")
    open(C.out("cases_check.txt"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("\n".join(L))
    sys.exit(1 if all_problems or within or taken else 0)


if __name__ == "__main__":
    main()
