#!/usr/bin/env python3
"""backfill_dicom_regen.py — data-office backfill for no-DICOM MRI placeholders.

THE missing piece of the no-DICOM regeneration story (2026-07-16): a
worklist-driven pass that FILLS the empty `<ACQ-ID>.data/` placeholders in
/raw/ from the staged ParaVision sources, keeping each acquisition's existing
ACQ-ID. This is the `recover_subject_metadata.py` recovery pattern — a
controlled in-place update of an already-registered acquisition — NOT a
re-ingest: the ingest's dedup would skip every registered row, and bypassing
the dedup would mint a NEW ACQ-ID and append a duplicate registry row (the
design trap this tool exists to avoid; see
tasks/dicom_regen_backfill_handoff.md §4.1).

WHAT IT DOES (per worklist row with status=="pending")
    1. locate the staged source exam under --staging
       (`<staging>/PV<paravision_version>/<study>/<exam>` from `original_name`
       — staged read-only from the platform host by
       tools/pull_pending_dicom_sources.py);
    2. re-check it is really an image exam (`is_nonimage_exam`) — a
       spectroscopy/calibration row is corrected to "not-applicable", exactly
       as the live ingest queue site classifies;
    3. regenerate + copy via the SAME code path as an ingest-time regen —
       `ingest_raw.copy_mri_paravision(..., auto_regenerate_dicom=True)`
       (Dicomifier + the two PV-7 workarounds; per-file sha256 verify during
       copy) — into the EXISTING `<ACQ-ID>.data/`, so the result is
       byte-identical to what a Dicomifier-equipped ingest would have written;
    4. VERIFY-after-write: re-hash every file on disk against the copy-time
       checksums AND run the PixelSpacing axis-order validation
       (validate_dicomifier_pixelspacing). On failure the freshly written
       DICOMs are removed (the placeholder is restored) and the row stays
       pending — `.data/` populated always implies verified data;
    5. refresh the acquisition's bookkeeping: checksums.json (was empty),
       sidecar `subject.age_at_acquisition` (blank-only fill, derived from
       date_of_birth + the now-real acquisition date — closes the last of the
       2026-07-15 age bug), README.txt (the three stale lines only);
    6. update the REGISTRY ROW in place (registry.update_row, the capability
       added for this tool): file_count / file_size_mb / checksum_present, and
       — blank-only — acquisition_datetime (from the regenerated DICOM's
       StudyDate+StudyTime) and file_format. NEVER overwrites a real value;
    7. flip the worklist row to status="regenerated". Steps 6-7 run inside ONE
       registry_lock critical section, so a crash never leaves the registry
       and the worklist disagreeing about a completed exam.

CRASH RECOVERY / RECONCILE. If a previous --apply run died between steps 3
and 7, the row is still "pending" but its `.data/` is populated. Such a row is
NOT regenerated again (never touch existing data): it is RECONCILED — the
on-disk DICOMs are re-verified (hash + PixelSpacing) and steps 5-7 completed
from what is on disk.

THE 94 NO-SOURCE ROWS. A pending row whose staged source has NO
`pdata/<idx>/2dseq` anywhere cannot be regenerated by Dicomifier — ever (80
header-only + 14 fid-only exams, verified 2026-07-16). They are reported, and
flipped to the terminal status "no-source" ONLY under the explicit
--mark-no-source flag (a human-gated call, mirroring the precedent's
"never auto-mark unresolvable"); without the flag they just stay pending.

SAFEGUARDS (mirroring recover_subject_metadata.py)
    * DRY-RUN by default — reports what WOULD happen, touches NOTHING
      (no Dicomifier runs either). Writing requires --apply.
    * Controlled write — registry fields that can already hold a real value
      (acquisition_datetime, file_format) are filled ONLY when blank; the
      sidecar fill touches ONLY a blank subject.age_at_acquisition.
    * VERIFY-AFTER-WRITE with rollback (step 4) before any bookkeeping.
    * IDEMPOTENT — rows already regenerated / not-applicable / no-source are
      skipped; a populated pending row reconciles instead of re-regenerating.
    * One-exam error isolation — a failure is recorded and the walk continues.

Usage (regeneration itself must run from WSL — Dicomifier is Linux/conda;
see the runbook / 11_OPERATIONS: `conda activate dicomifier-pilot`):

    # Preview everything (safe anywhere, no Dicomifier needed):
    PYTHONPATH=tools python tools/backfill_dicom_regen.py

    # Regenerate one exam as a pilot, then the rest (from WSL):
    PYTHONPATH=tools python tools/backfill_dicom_regen.py --apply --limit 1
    PYTHONPATH=tools python tools/backfill_dicom_regen.py --apply

    # Record the un-regenerable rows (data-office decision 2026-07-16):
    PYTHONPATH=tools python tools/backfill_dicom_regen.py --apply --mark-no-source

    # After a WSL --apply run: rebuild project hard-links FROM WINDOWS
    # (os.link is refused over the CIFS mount from WSL):
    python tools/relink_mri_regen.py --nas-root J:/gjesus3-data

NOTE: the sidecar's `mri:` block is deliberately NOT rewritten — it faithfully
carries the JCAMP-DX parse from ingest time, which is unchanged by the regen;
the per-frame DICOM headers now live in the DICOMs themselves in `.data/`.
"""

import argparse
import ast
import json
import os
import shutil
import sys
from datetime import datetime

# tools/ on sys.path so `from ingest import ...` works whether run from the
# repo root or from tools/ (mirrors the other CLIs).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ingest import checksum, locking, paravision_regen, pending_dicom, registry, resolver  # noqa: E402
import animal_db  # noqa: E402  (age_iso8601 is pure; no DB connection made)


def log(msg, level="INFO"):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {level}: {msg}", file=sys.stderr)


# --------------------------------------------------------------- path helpers

def _first_existing(*candidates):
    for c in candidates:
        if c and os.path.isdir(c):
            return c
    return candidates[0]


def default_nas_root():
    return os.environ.get("GJESUS3_ROOT") or _first_existing(
        "/mnt/gjesus3/gjesus3-data", "J:/gjesus3-data")


def default_staging():
    return _first_existing(r"D:\temp\mri_regen_20260715",
                           "/mnt/d/temp/mri_regen_20260715")


def staged_exam_path(staging, row):
    """`<staging>/PV<version>/<study>/<exam>` for a worklist row, or None."""
    pv = (row.get("paravision_version") or "").strip()
    study, _, exam = (row.get("original_name") or "").partition("/")
    if not pv or not study or not exam:
        return None
    return os.path.join(staging, f"PV{pv}", study, exam)


def has_2dseq(exam_path):
    """True when any pdata/<idx>/2dseq exists — Dicomifier's required input."""
    pdata = os.path.join(exam_path, "pdata")
    if not os.path.isdir(pdata):
        return False
    for idx in os.listdir(pdata):
        if os.path.isfile(os.path.join(pdata, idx, "2dseq")):
            return True
    return False


def no_source_kind(exam_path):
    """'fid-only' or 'header-only' for an exam without 2dseq (log detail)."""
    return ("fid-only" if os.path.isfile(os.path.join(exam_path, "fid"))
            else "header-only")


def acq_dir_of(nas_root, row):
    """Absolute acquisition folder from the row's share-relative canonical_path."""
    rel = (row.get("canonical_path") or "").strip().strip("/")
    if not rel:
        return None
    return os.path.join(nas_root, rel.replace("/", os.sep))


def data_dir_of(acq_dir, acq_id):
    return os.path.join(acq_dir, f"{acq_id}.data")


# ----------------------------------------------------------- value conversion

def parse_reconstructions(value):
    """Worklist `reconstructions` (a str()-ified YAML value) -> the live form.

    The enrolment stored `str(ingest.reconstructions)`; convert back so the
    regen honours the SAME recon selection the original ingest would have.
    '' / 'None' -> None; 'all' -> 'all'; '3' -> '3' (a single index);
    '[1, 3]' -> [1, 3]. Anything unparseable is passed through as the string
    (paravision_metadata._normalize_reconstructions raises on true garbage).
    """
    s = (value or "").strip()
    if s in ("", "None"):
        return None
    if s.lower() == "all":
        return "all"
    if s.startswith("["):
        try:
            return ast.literal_eval(s)
        except (ValueError, SyntaxError):
            return s
    return s


def datetime_from_dicom_tags(study_date, study_time):
    """DICOM StudyDate ('20220128') + StudyTime ('085233[.frac]') -> registry ISO.

    Routed through resolver.normalize_acquisition_datetime so the value has
    exactly the shape a normal ingest would have written. '' when the date is
    missing/malformed (never guess).
    """
    d = (study_date or "").strip()
    t = (study_time or "").strip().split(".")[0]
    if len(d) != 8 or not d.isdigit():
        return ""
    if len(t) >= 6 and t[:6].isdigit():
        return resolver.normalize_acquisition_datetime(d + t[:6])
    return resolver.normalize_acquisition_datetime(d)


def acq_datetime_from_data_dir(data_dir):
    """Read the acquisition datetime from a regenerated DICOM in `.data/`.

    Uses study-level tags (StudyDate/StudyTime) from the first .dcm; every
    frame of an exam shares them. Returns '' if unreadable — the registry
    field is then simply left blank (controlled write, never guess).
    """
    try:
        import pydicom
    except ImportError:
        return ""
    try:
        dcms = sorted(f for f in os.listdir(data_dir)
                      if f.lower().endswith(".dcm"))
        if not dcms:
            return ""
        ds = pydicom.dcmread(os.path.join(data_dir, dcms[0]),
                             stop_before_pixels=True)
        return datetime_from_dicom_tags(str(getattr(ds, "StudyDate", "")),
                                        str(getattr(ds, "StudyTime", "")))
    except Exception:
        return ""


# ------------------------------------------------------------ on-disk helpers

def data_dir_inventory(data_dir):
    """(total_files, dcm_files) inside `.data/` (recursive)."""
    total = dcm = 0
    for _root, _dirs, files in os.walk(data_dir):
        for f in files:
            total += 1
            if f.lower().endswith(".dcm"):
                dcm += 1
    return total, dcm


def deposited_stats(acq_dir):
    """(dcm_count, size_mb) of what the acquisition folder holds, excluding the
    three bookkeeping files — the same walk the ingest uses for the registry
    (ingest_raw.py, 'Recompute file_count and size from the DESTINATION')."""
    size = 0
    dcm = 0
    for root, _dirs, files in os.walk(acq_dir):
        for fname in files:
            if fname in ("checksums.json", "metadata.json", "README.txt"):
                continue
            size += os.path.getsize(os.path.join(root, fname))
            if fname.lower().endswith(".dcm"):
                dcm += 1
    return dcm, round(size / 1_000_000, 1)


def verify_data_dir(acq_dir, data_dirname, checksums, log=log):
    """Verify-after-write: re-hash every checksummed file from disk + run the
    PixelSpacing axis-order validation. Returns (ok, detail)."""
    if not checksums:
        return False, "no checksums to verify"
    for rel, expected in checksums.items():
        path = os.path.join(acq_dir, rel.replace("/", os.sep))
        if not os.path.isfile(path):
            return False, f"missing after write: {rel}"
        actual = checksum.sha256_file(path)
        if actual != expected:
            return False, f"hash mismatch on re-read: {rel}"
    # PixelSpacing axis-order check (the PV-7 workaround must have applied).
    try:
        import validate_dicomifier_pixelspacing as vps
        counts = vps.analyse(data_dirname, os.path.join(acq_dir, data_dirname))
        if counts.get("matches_swapped", 0):
            return False, (f"{counts['matches_swapped']} series read as "
                           f"SWAPPED PixelSpacing — workaround did not apply")
    except ImportError:
        log("pydicom unavailable — PixelSpacing validation skipped", "WARN")
    return True, f"{len(checksums)} files re-hashed OK; PixelSpacing OK"


def remove_written_dicoms(acq_dir, checksums, log=log):
    """Roll back a failed-verify fill: delete exactly the files we wrote,
    restoring the empty placeholder. Never touches anything else."""
    for rel in checksums:
        path = os.path.join(acq_dir, rel.replace("/", os.sep))
        try:
            if os.path.isfile(path):
                os.remove(path)
        except OSError as e:
            log(f"rollback: could not remove {rel}: {e}", "ERROR")


# ------------------------------------------------------- bookkeeping refresh

def update_sidecar_age(sidecar_path, acq_datetime):
    """Blank-only fill of subject.age_at_acquisition from date_of_birth + the
    now-real acquisition datetime. Atomic write + verify + rollback (the
    recover_subject_metadata pattern). Returns a short outcome string."""
    try:
        with open(sidecar_path, "r", encoding="utf-8") as f:
            sidecar = json.load(f)
    except Exception as e:
        return f"error: could not read sidecar ({e})"
    subject = sidecar.get("subject")
    if not isinstance(subject, dict):
        return "skipped: no subject block"
    if (subject.get("age_at_acquisition") or "").strip():
        return "skipped: age already populated"
    dob = (subject.get("date_of_birth") or "").strip()
    if not dob:
        return "skipped: no date_of_birth"
    if not acq_datetime:
        return "skipped: no acquisition datetime"
    age = animal_db.age_iso8601(dob, acq_datetime)
    if not age:
        return "skipped: age underivable from values"

    backup = dict(subject)
    subject["age_at_acquisition"] = age
    tmp = sidecar_path + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(sidecar, f, indent=2, ensure_ascii=False)
            f.write("\n")
        os.replace(tmp, sidecar_path)
        with open(sidecar_path, "r", encoding="utf-8") as f:
            fresh = json.load(f)
        if (fresh.get("subject") or {}).get("age_at_acquisition") != age:
            raise RuntimeError("verify-after-write mismatch")
    except Exception as e:
        sidecar["subject"] = backup
        try:
            with open(tmp, "w", encoding="utf-8") as f:
                json.dump(sidecar, f, indent=2, ensure_ascii=False)
                f.write("\n")
            os.replace(tmp, sidecar_path)
        except Exception:
            pass
        return f"error: {e} (rolled back)"
    return f"filled age_at_acquisition={age}"


def refresh_readme(acq_dir, acq_date_iso, file_count, size_mb):
    """Refresh ONLY the three now-stale README.txt lines (acquisition date /
    file count / total size). Everything else — including the original
    Registration Date — is preserved verbatim; regenerating the whole README
    would falsify it. Best-effort: returns a short outcome string."""
    path = os.path.join(acq_dir, "README.txt")
    if not os.path.isfile(path):
        return "skipped: no README.txt"
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        date_part = (acq_date_iso or "").split("T", 1)[0]
        replaced = 0
        for i, line in enumerate(lines):
            if line.startswith("Acquisition Date :") and date_part:
                if line.split(":", 1)[1].strip() in ("unknown", ""):
                    lines[i] = f"Acquisition Date : {date_part}\n"
                    replaced += 1
            elif line.startswith("File Count       :"):
                lines[i] = f"File Count       : {file_count}\n"
                replaced += 1
            elif line.startswith("Total Size (MB)  :"):
                lines[i] = f"Total Size (MB)  : {size_mb}\n"
                replaced += 1
        if not replaced:
            return "skipped: no matching lines"
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.writelines(lines)
        os.replace(tmp, path)
        return f"refreshed {replaced} line(s)"
    except Exception as e:
        return f"error: {e}"


# ------------------------------------------------------------- the core pass

def finish_bookkeeping(row, ctx, checksums, *, reconciled):
    """Steps 5-7 for one exam whose `.data/` now holds verified DICOMs:
    checksums.json, sidecar age, README, then — inside ONE lock — the registry
    row update and the worklist flip. Returns (ok, detail)."""
    acq_id = row["acq_id"]
    acq_dir = acq_dir_of(ctx["nas_root"], row)
    data_dir = data_dir_of(acq_dir, acq_id)

    checksum.write_checksums(checksums,
                             os.path.join(acq_dir, "checksums.json"))

    acq_dt = acq_datetime_from_data_dir(data_dir)
    if not acq_dt:
        log(f"{acq_id}: no readable StudyDate in the regenerated DICOMs — "
            f"acquisition_datetime left as-is", "WARN")

    age_note = update_sidecar_age(os.path.join(acq_dir, "metadata.json"),
                                  acq_dt)
    log(f"{acq_id}: sidecar age: {age_note}",
        "ERROR" if age_note.startswith("error") else "INFO")

    dcm_count, size_mb = deposited_stats(acq_dir)
    readme_note = refresh_readme(acq_dir, acq_dt, dcm_count, size_mb)
    log(f"{acq_id}: README: {readme_note}")

    updates = {
        "file_count": str(dcm_count),
        "file_size_mb": str(size_mb),
        "checksum_present": "Y",
        "acquisition_datetime": acq_dt,
        "file_format": ".dcm",
    }
    if not acq_dt:
        del updates["acquisition_datetime"]

    reg_path = os.path.join(ctx["registries_dir"], "registry_raw.csv")
    wl_path = pending_dicom.pending_dicom_path(ctx["registries_dir"])
    with locking.registry_lock(ctx["registries_dir"], log=log):
        found, applied, skipped = registry.update_row(
            reg_path, acq_id, updates,
            only_if_blank=("acquisition_datetime", "file_format"))
        if not found:
            return False, "registry row not found — worklist row NOT flipped"
        # Worklist flip: read-modify-write INSIDE the same lock, so a
        # concurrently enrolling ingest can't be clobbered and a crash can't
        # leave registry and worklist disagreeing about this exam.
        pending_dicom._assert_header(wl_path)
        rows = pending_dicom.read_pending_dicom(wl_path)
        me = next((r for r in rows if r.get("acq_id") == acq_id), None)
        if me is None:
            return False, "worklist row vanished mid-run — inspect by hand"
        me["status"] = "regenerated"
        pending_dicom._write_all(wl_path, rows)

    for field, existing in skipped.items():
        log(f"{acq_id}: registry {field} kept existing real value "
            f"{existing!r} (controlled write)")
    verb = "reconciled" if reconciled else "regenerated"
    return True, (f"{verb}: {dcm_count} DICOMs, {size_mb} MB; registry "
                  f"updated ({sorted(applied)}); worklist -> regenerated")


def process_row(row, ctx):
    """One worklist row -> a result dict {acq_id, outcome, detail}."""
    acq_id = (row.get("acq_id") or "").strip()
    status = (row.get("status") or "").strip()
    apply = ctx["apply"]
    res = {"acq_id": acq_id, "outcome": "", "detail": ""}

    def done(outcome, detail=""):
        res["outcome"], res["detail"] = outcome, detail
        return res

    if status != "pending":
        return done("skipped-status", f"status={status!r}")
    if (row.get("nonimage_marker") or "").strip():
        return done("anomaly", "pending row carries a nonimage_marker — "
                               "should be not-applicable; inspect by hand")

    acq_dir = acq_dir_of(ctx["nas_root"], row)
    if not acq_dir or not os.path.isdir(acq_dir):
        return done("error", f"acquisition folder missing: {acq_dir}")
    data_dir = data_dir_of(acq_dir, acq_id)
    if not os.path.isdir(data_dir):
        return done("error", f"no {acq_id}.data/ folder — not a placeholder")
    sidecar = os.path.join(acq_dir, "metadata.json")
    if not os.path.isfile(sidecar):
        return done("error", "metadata.json missing — inspect by hand")

    n_files, n_dcm = data_dir_inventory(data_dir)

    # --- crash-recovery reconcile: data already present but row still pending.
    if n_files:
        if not n_dcm:
            return done("error", f".data/ holds {n_files} non-DICOM file(s) — "
                                 f"inspect by hand")
        if not apply:
            return done("would-reconcile",
                        f".data/ already holds {n_dcm} DICOMs; would verify "
                        f"and complete bookkeeping (no regeneration)")
        recomputed = {}
        for root, _dirs, files in os.walk(data_dir):
            for f in sorted(files):
                p = os.path.join(root, f)
                rel = os.path.relpath(p, acq_dir).replace(os.sep, "/")
                recomputed[rel] = checksum.sha256_file(p)
        ok, detail = verify_data_dir(acq_dir, f"{acq_id}.data", recomputed)
        if not ok:
            return done("error", f"reconcile verify failed: {detail} — "
                                 f"data left in place; inspect by hand")
        ok, detail = finish_bookkeeping(row, ctx, recomputed, reconciled=True)
        return done("reconciled" if ok else "error", detail)

    # --- locate + qualify the staged source.
    exam = staged_exam_path(ctx["staging"], row)
    if not exam or not os.path.isdir(exam):
        return done("source-missing", f"staged source not found: {exam} — "
                                      f"re-pull (pull_pending_dicom_sources.py)")

    nonimage, marker = paravision_regen.is_nonimage_exam(exam)
    if nonimage:
        if not apply:
            return done("would-correct-not-applicable",
                        f"method matches {marker!r}")
        wl_path = pending_dicom.pending_dicom_path(ctx["registries_dir"])
        with locking.registry_lock(ctx["registries_dir"], log=log):
            rows = pending_dicom.read_pending_dicom(wl_path)
            me = next((r for r in rows if r.get("acq_id") == acq_id), None)
            if me is not None:
                me["status"] = "not-applicable"
                me["nonimage_marker"] = marker
                pending_dicom._write_all(wl_path, rows)
        return done("corrected-not-applicable", f"method matches {marker!r}")

    if not has_2dseq(exam):
        kind = no_source_kind(exam)
        if not ctx["mark_no_source"]:
            return done("no-source-unmarked",
                        f"{kind}; stays pending (run --mark-no-source to "
                        f"record it)")
        if not apply:
            return done("would-mark-no-source", kind)
        wl_path = pending_dicom.pending_dicom_path(ctx["registries_dir"])
        with locking.registry_lock(ctx["registries_dir"], log=log):
            rows = pending_dicom.read_pending_dicom(wl_path)
            me = next((r for r in rows if r.get("acq_id") == acq_id), None)
            if me is not None:
                me["status"] = "no-source"
                pending_dicom._write_all(wl_path, rows)
        return done("marked-no-source", kind)

    # --- the regenerable case.
    if not apply:
        return done("would-regenerate", f"source ready: {exam}")

    import ingest_raw  # heavier import (yaml etc.); only needed to write
    recons = parse_reconstructions(row.get("reconstructions"))
    try:
        checksums = ingest_raw.copy_mri_paravision(
            exam, acq_dir, acq_id, recons, log, auto_regenerate_dicom=True)
    except RuntimeError as e:
        return done("error", f"regeneration failed: {e}")
    if not checksums:
        # copy_mri_paravision fell through to the placeholder path — the regen
        # produced nothing. The .data/ is still empty; the row stays pending.
        return done("error", "regeneration produced no DICOMs (see log)")

    ok, detail = verify_data_dir(acq_dir, f"{acq_id}.data", checksums)
    if not ok:
        remove_written_dicoms(acq_dir, checksums)
        return done("error", f"verify-after-write FAILED ({detail}); "
                             f"written DICOMs removed, placeholder restored")

    ok, detail = finish_bookkeeping(row, ctx, checksums, reconciled=False)
    return done("regenerated" if ok else "error", detail)


def run(ctx):
    wl_path = pending_dicom.pending_dicom_path(ctx["registries_dir"])
    rows = pending_dicom.read_pending_dicom(wl_path)
    if not rows:
        log(f"worklist empty or missing: {wl_path}", "ERROR")
        return {"counts": {"error": 1}, "results": []}
    log(f"worklist: {wl_path} ({len(rows)} rows)")

    if ctx["acq_ids"]:
        want = set(ctx["acq_ids"])
        rows = [r for r in rows if (r.get("acq_id") or "").strip() in want]
        log(f"--acq-id filter: {len(rows)} row(s) selected")

    results = []
    counts = {}
    n_worked = 0  # regen/reconcile attempts, for --limit
    for row in rows:
        if (row.get("status") or "").strip() != "pending":
            continue  # not part of the drain set; not even reported
        if ctx["limit"] and n_worked >= ctx["limit"]:
            results.append({"acq_id": row.get("acq_id", ""),
                            "outcome": "deferred-limit", "detail": ""})
            counts["deferred-limit"] = counts.get("deferred-limit", 0) + 1
            continue
        try:
            r = process_row(row, ctx)
        except Exception as e:  # noqa: BLE001 — one bad exam must not kill the walk
            r = {"acq_id": row.get("acq_id", ""), "outcome": "error",
                 "detail": f"unexpected: {e}"}
        results.append(r)
        counts[r["outcome"]] = counts.get(r["outcome"], 0) + 1
        if r["outcome"] in ("regenerated", "reconciled", "would-regenerate",
                            "would-reconcile", "error"):
            n_worked += 1
        log(f"[{r['outcome'].upper()}] {r['acq_id']}: {r['detail']}")

    return {"counts": counts, "results": results}


def main(argv=None):
    p = argparse.ArgumentParser(
        description=__doc__.splitlines()[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="DRY-RUN by default; --apply writes. Regeneration requires "
               "Dicomifier on PATH (WSL, conda env dicomifier-pilot). After a "
               "WSL run, rebuild project links from Windows: "
               "python tools/relink_mri_regen.py",
    )
    p.add_argument("--nas-root", default=default_nas_root(),
                   help="NAS root containing registries/ (default: "
                        "$GJESUS3_ROOT, else the first mounted of "
                        "/mnt/gjesus3/gjesus3-data or J:/gjesus3-data)")
    p.add_argument("--staging", default=default_staging(),
                   help="staged ParaVision sources (pull_pending_dicom_sources"
                        ".py layout: <staging>/PV<ver>/<study>/<exam>)")
    p.add_argument("--apply", action="store_true",
                   help="write changes (default: dry-run preview)")
    p.add_argument("--limit", type=int, default=0,
                   help="cap regeneration/reconcile attempts this run "
                        "(pilot: --limit 1)")
    p.add_argument("--acq-id", action="append", dest="acq_ids", default=[],
                   help="process only this ACQ-ID (repeatable)")
    p.add_argument("--mark-no-source", action="store_true",
                   help="flip pending rows whose staged source has no "
                        "pdata/<idx>/2dseq to the terminal status "
                        "'no-source' (human-gated; without this they stay "
                        "pending and are only reported)")
    args = p.parse_args(argv)

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass

    nas_root = os.path.normpath(args.nas_root)
    registries_dir = os.path.join(nas_root, "registries")
    if not os.path.isdir(registries_dir):
        log(f"NAS root does not look valid: {nas_root!r} (no registries/). "
            f"Pass --nas-root or set GJESUS3_ROOT.", "ERROR")
        return 2
    log(f"NAS root : {nas_root}")
    log(f"staging  : {args.staging}")
    if not args.apply:
        log("*** DRY-RUN — nothing will be written (use --apply) ***")
    else:
        ok, ver = paravision_regen.check_dicomifier_available()
        if ok:
            log(f"Dicomifier available: {ver}")
        else:
            log("Dicomifier NOT on PATH — regeneration will fail per-exam. "
                "Reconcile/--mark-no-source still work. (Run from WSL with "
                "`conda activate dicomifier-pilot` to regenerate.)", "WARN")

    ctx = {
        "nas_root": nas_root,
        "registries_dir": registries_dir,
        "staging": args.staging,
        "apply": args.apply,
        "limit": args.limit,
        "acq_ids": args.acq_ids,
        "mark_no_source": args.mark_no_source,
    }
    summary = run(ctx)

    log("---- summary ----")
    log(f"mode: {'APPLY' if args.apply else 'DRY-RUN'}")
    for outcome in sorted(summary["counts"]):
        log(f"  {outcome:<28} {summary['counts'][outcome]}")
    errors = summary["counts"].get("error", 0)
    if errors:
        log(f"{errors} error(s) — see per-row lines above", "ERROR")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
